#include "Tools/Blueprint/BlueprintFindingUtils.h"

#include "Tools/Blueprint/BlueprintToolUtils.h"
#include "Utils/McpAssetModifier.h"
#include "Utils/McpV2ToolUtils.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Engine/Blueprint.h"
#include "K2Node.h"
#include "K2Node_CallFunction.h"
#include "K2Node_FunctionResult.h"
#include "K2Node_Variable.h"

namespace
{
	bool HasPinDefaultValue(const UEdGraphPin* Pin)
	{
		return Pin
			&& (Pin->DefaultObject != nullptr
				|| !Pin->DefaultValue.IsEmpty()
				|| !Pin->AutogeneratedDefaultValue.IsEmpty()
				|| !Pin->DefaultTextValue.IsEmpty()
				|| Pin->bDefaultValueIsIgnored);
	}

	bool ShouldInspectGraph(const UBlueprint* Blueprint, const UEdGraph* Graph, const BlueprintFindingUtils::FQuery& Query)
	{
		if (!Graph)
		{
			return false;
		}

		if (!Query.GraphNameFilter.IsEmpty()
			&& !Graph->GetName().Equals(Query.GraphNameFilter, ESearchCase::IgnoreCase))
		{
			return false;
		}

		if (!Query.GraphTypeFilter.IsEmpty())
		{
			const FString GraphType = McpV2ToolUtils::GetBlueprintGraphType(Blueprint, Graph);
			if (!GraphType.Equals(Query.GraphTypeFilter, ESearchCase::IgnoreCase))
			{
				return false;
			}
		}

		return true;
	}

	bool InterfaceNeedsImplementationGraph(const UClass* InterfaceClass)
	{
		if (!InterfaceClass)
		{
			return false;
		}

		const UClass* IterationClass = InterfaceClass;
		if (const UBlueprint* InterfaceBlueprint = Cast<UBlueprint>(InterfaceClass->ClassGeneratedBy))
		{
			for (UEdGraph* FunctionGraph : InterfaceBlueprint->FunctionGraphs)
			{
				if (!FunctionGraph)
				{
					continue;
				}

				for (UEdGraphNode* Node : FunctionGraph->Nodes)
				{
					if (Cast<UK2Node_FunctionResult>(Node))
					{
						return true;
					}
				}
			}

			if (InterfaceBlueprint->SkeletonGeneratedClass)
			{
				IterationClass = InterfaceBlueprint->SkeletonGeneratedClass;
			}
		}

		for (TFieldIterator<UFunction> FunctionIter(IterationClass, EFieldIteratorFlags::IncludeSuper); FunctionIter; ++FunctionIter)
		{
			const UFunction* Function = *FunctionIter;
			if (Function
				&& UEdGraphSchema_K2::CanKismetOverrideFunction(Function)
				&& !UEdGraphSchema_K2::FunctionCanBePlacedAsEvent(Function))
			{
				return true;
			}
		}

		return false;
	}

	TSharedPtr<FJsonObject> MakeFinding(
		const FString& Code,
		const FString& Severity,
		const FString& Message,
		const FString& GraphName,
		UEdGraphNode* Node,
		const FString& AssetPath,
		const FString& SessionId)
	{
		TSharedPtr<FJsonObject> Finding = MakeShareable(new FJsonObject);
		Finding->SetStringField(TEXT("code"), Code);
		Finding->SetStringField(TEXT("severity"), Severity);
		Finding->SetStringField(TEXT("message"), Message);
		Finding->SetStringField(TEXT("graph_name"), GraphName);

		if (Node)
		{
			const FString NodeGuid = Node->NodeGuid.ToString(EGuidFormats::DigitsWithHyphens);
			Finding->SetStringField(TEXT("node_guid"), NodeGuid);
			if (!SessionId.IsEmpty())
			{
				Finding->SetObjectField(
					TEXT("handle"),
					McpV2ToolUtils::MakeEntityHandle(
						TEXT("blueprint_node"),
						SessionId,
						AssetPath,
						NodeGuid,
						Node->GetNodeTitle(ENodeTitleType::ListView).ToString()));
			}
		}

		return Finding;
	}
}

namespace BlueprintFindingUtils
{
	TArray<TSharedPtr<FJsonValue>> CollectFindings(UBlueprint* Blueprint, const FQuery& Query)
	{
		TArray<TSharedPtr<FJsonValue>> Findings;
		if (!Blueprint)
		{
			return Findings;
		}

		const int32 MaxFindings = FMath::Max(1, Query.MaxFindings);

		for (const FBPInterfaceDescription& InterfaceDescription : Blueprint->ImplementedInterfaces)
		{
			if (Findings.Num() >= MaxFindings)
			{
				break;
			}

			const UClass* InterfaceClass = InterfaceDescription.Interface.Get();
			if (!InterfaceClass
				|| InterfaceDescription.Graphs.Num() > 0
				|| !InterfaceNeedsImplementationGraph(InterfaceClass))
			{
				continue;
			}

			const FString InterfaceName = InterfaceClass->GetName();
			Findings.Add(MakeShareable(new FJsonValueObject(
				MakeFinding(
					TEXT("missing_interface_graph"),
					TEXT("error"),
					FString::Printf(TEXT("Interface '%s' has no generated implementation graphs"), *InterfaceName),
					InterfaceName,
					nullptr,
					Query.AssetPath,
					Query.SessionId))));
		}

		TArray<UEdGraph*> Graphs;
		FMcpAssetModifier::GetAllSearchableGraphs(Blueprint, Graphs);

		for (UEdGraph* Graph : Graphs)
		{
			if (Findings.Num() >= MaxFindings || !ShouldInspectGraph(Blueprint, Graph, Query))
			{
				continue;
			}

			for (UEdGraphNode* Node : Graph->Nodes)
			{
				if (!Node || Findings.Num() >= MaxFindings)
				{
					continue;
				}

				bool bNodeHasOrphanPin = false;
				for (UEdGraphPin* Pin : Node->Pins)
				{
					if (Pin && Pin->bOrphanedPin)
					{
						Findings.Add(MakeShareable(new FJsonValueObject(
							MakeFinding(
								TEXT("orphan_pin"),
								TEXT("warning"),
								FString::Printf(TEXT("Node '%s' contains orphan pin '%s'"), *Node->GetNodeTitle(ENodeTitleType::ListView).ToString(), *Pin->PinName.ToString()),
								Graph->GetName(),
								Node,
								Query.AssetPath,
								Query.SessionId))));
						bNodeHasOrphanPin = true;
						break;
					}
				}

				if (Findings.Num() >= MaxFindings)
				{
					break;
				}

				if (!bNodeHasOrphanPin && Node->HasDeprecatedReference())
				{
					Findings.Add(MakeShareable(new FJsonValueObject(
						MakeFinding(
							TEXT("broken_or_deprecated_reference"),
							TEXT("warning"),
							FString::Printf(TEXT("Node '%s' references a deprecated or invalid member"), *Node->GetNodeTitle(ENodeTitleType::ListView).ToString()),
							Graph->GetName(),
							Node,
							Query.AssetPath,
							Query.SessionId))));
				}

				if (Findings.Num() >= MaxFindings)
				{
					break;
				}

				if (const UK2Node_CallFunction* CallFunctionNode = Cast<UK2Node_CallFunction>(Node))
				{
					if (!CallFunctionNode->GetTargetFunction())
					{
						Findings.Add(MakeShareable(new FJsonValueObject(
							MakeFinding(
								TEXT("unresolved_member_reference"),
								TEXT("error"),
								FString::Printf(TEXT("Call function node '%s' could not resolve its target function"), *Node->GetNodeTitle(ENodeTitleType::ListView).ToString()),
								Graph->GetName(),
								Node,
								Query.AssetPath,
								Query.SessionId))));
					}
				}
				else if (const UK2Node_Variable* VariableNode = Cast<UK2Node_Variable>(Node))
				{
					if (!VariableNode->GetPropertyForVariable())
					{
						Findings.Add(MakeShareable(new FJsonValueObject(
							MakeFinding(
								TEXT("unresolved_member_reference"),
								TEXT("error"),
								FString::Printf(TEXT("Variable node '%s' could not resolve its referenced property"), *Node->GetNodeTitle(ENodeTitleType::ListView).ToString()),
								Graph->GetName(),
								Node,
								Query.AssetPath,
								Query.SessionId))));
					}
				}

				if (Findings.Num() >= MaxFindings)
				{
					break;
				}

				for (UEdGraphPin* Pin : Node->Pins)
				{
					if (!Pin
						|| Pin->Direction != EGPD_Input
						|| Pin->bHidden
						|| Pin->LinkedTo.Num() > 0
						|| Pin->bNotConnectable)
					{
						continue;
					}

					if (Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec)
					{
						const UK2Node* K2Node = Cast<UK2Node>(Node);
						if (!K2Node || K2Node->IsNodePure())
						{
							continue;
						}

						Findings.Add(MakeShareable(new FJsonValueObject(
							MakeFinding(
								TEXT("unlinked_required_pin"),
								TEXT("error"),
								FString::Printf(TEXT("Node '%s' has an unlinked required exec pin '%s'"), *Node->GetNodeTitle(ENodeTitleType::ListView).ToString(), *Pin->PinName.ToString()),
								Graph->GetName(),
								Node,
								Query.AssetPath,
								Query.SessionId))));
					}
					else if (!HasPinDefaultValue(Pin))
					{
						Findings.Add(MakeShareable(new FJsonValueObject(
							MakeFinding(
								TEXT("missing_default_value"),
								TEXT("warning"),
								FString::Printf(TEXT("Pin '%s' on node '%s' has no link and no default value"), *Pin->PinName.ToString(), *Node->GetNodeTitle(ENodeTitleType::ListView).ToString()),
								Graph->GetName(),
								Node,
								Query.AssetPath,
								Query.SessionId))));
					}

					if (Findings.Num() >= MaxFindings)
					{
						break;
					}
				}
			}
		}

		return Findings;
	}
}
